server-id: 'Development'
translations: './lang'
server-list: 'https://raw.githubusercontent.com/ShootGame/Servers/master/servers.yml'

mongo:
  uri: 'mongodb://127.0.0.1:27017'
  database: 'shg'

servers:
  uri: 'mongodb://127.0.0.1:27017'
  database: 'servers'
  collection: 'public-servers'
